### ISSUE TITLE
CSS: Select typeahead gets incorrect CSS from upstream

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3150]
Right now the react-core distribution has a code snippet for Select#Typeahead which looks as follows.
```scss
// When the input is the first thing then use a negative left padding so it matches the toggle container
input:first-child {
  margin-left: calc(-1 * var(--pf-c-select__toggle--PaddingLeft));
}
```
Upstream there isn't anything about this, instead I can find these lines  
https://github.com/patternfly/patternfly-next/blob/6ccd07725a8649febc9090d2d3e62219079b9bb8/src/patternfly/components/Select/select.scss#L312-L318

This issue is causing padding issues for the select boxes on my application
![image](https://user-images.githubusercontent.com/6598829/66925702-1ea78380-f02d-11e9-88fe-65b73fffa8f0.png)

Slack conversation
> egustavs 14:58
> I wanted to add, the CSS I see on patternfly-next is different, which instead targets form:first-child. It's only for the react-core builds I see the above input:first-child issue
> 
> egustavs 11:48
> zack do you think the above issue I have is a PF build mishap?
> 
> zack 15:45
> egustavs I doubt it's a PF build mishap. It's more likely related to CSS being wrong or being applied in the wrong place. I don't have a lot of time to debug it now but might have time in the future.

cc @redallen
