### ISSUE TITLE
GitHub actions should be used to check PR requirements have been met

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#3342]
In our contribution guide, we have several requirements for merging PR's that we should enforce with github actions.

1) Check that an approved issue exists
2) Verify the commit message follows the conventional commit message standard

**Comment by evwilkin** [comment]
Possibly helpful: https://github.com/marketplace/commit-message-lint

**Comment by dgutride** [comment]
cc: @rh-uxd/teams/test-team

**Comment by dgutride** [comment]
cc: @rh-uxd/test-team

**Comment by dgutride** [comment]
@rh-uxd/test-team

**Comment by redallen** [comment]
I figured out [what event](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request) to use to go about doing this:
```yml
name: Verify PR text
on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  build:
    name: Check PR Title/Body
    runs-on: ubuntu-latest
    steps:
      - name: Echo the PR title
        run: echo '${{ github.event.pull_request.title }}'
      - name: Echo the PR text
        run: echo '${{ github.event.pull_request.body }}'
```

Unfortunately, there isn't an easy way to hook up the results of shell commands to Github Check that goes at the bottom of a PR. It's possible, however, using Github's Check API manually in a script:
```js
const core = require("@actions/core");
const github = require("@actions/github");

async function run() {
  try {
    const [
      gitHubRepoOwner,
      gitHubRepoName
    ] = process.env.GITHUB_REPOSITORY.split("/");
    const gitHubSha = process.env.GITHUB_SHA;
    const gitHubToken = core.getInput("github-token");

    const octokit = new github.GitHub(gitHubToken);

    octokit.checks.create({
      owner: gitHubRepoOwner,
      repo: gitHubRepoName,
      name: "Check Created by API",
      head_sha: gitHubSha,
      status: "completed",
      conclusion: "success",
      output: {
        title: "Check Created by API",
        summary: `Pass/fail`
      }
    });

    core.setOutput("time", new Date().toTimeString());
  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
```
