### ISSUE TITLE
PF4: Component CSS imports 

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#682]
Currently, each PF4 component imports CSS from pf-next. So far, importing CSS has been working for most components. However, I encountered a problem with the new backgroundImage component relying on CSS image paths.

`import styles from '@patternfly/patternfly-next/components/BackgroundImage/styles.css';`

The CSS image path from pf-next looks something like this.

```
background-image: url("../../assets/images/pfbg_2000.jpg");
```

Out of the box, these paths work when patternfly.css is included in the page. However, the paths are not relevant when building components in react-core. We can see the dark gray background when using the pf-c-background-image selector, but the image path cannot be resolved.

I'm thinking react-core may need to build scss files, and distribute its own CSS, relative to the components and images within its own package? That way, we could modify the $pf-global--image-path variable of pf-next to work with an image delivered by react-core.

**Comment by dmiller9911** [comment]
This was a concern I had with core providing images and other assets as urls in the CSS. It is next to impossible to overwrite from a component stand point. These urls should be driven by props. If a user wants to use their own background image that should be able to be overwritten/specified by a prop. It might be a good idea to edit the Babel plugin that outputs the CSS to remove the background image paths. Then inside the component we could map that based on src prop similar to avatar and brand.

**Comment by dlabrecq** [comment]
Thanks for the suggestion, Doug. Hope you're enjoying you're new gig!

I thought about adding a prop similar to brand, but backed off considering pf-c-background-image is associated with 10 images, due to various screen sizes -- that's 9 screens plus an overlay image. I was asked to create a PR now to unblock Amiee.

**Comment by dmiller9911** [comment]
Totally agree it is something that should be talked about. I think going back to SASS is a bad idea for the React repo. It is a slippery slope toward mixins and massive CSS files that are not modular. For the multiple possible images this could be accomplished two ways that would avoid using SASS and requiring uses to setup sass paths and sass loaders, sass variables, et.

1. Core could provide CSS Variables for the BG image URLs. This matches how things are set up already and would honestly be one of the better approaches since it will stay consistent
```css
.pf-c-background-image {
  --pf-c-background-image--BackgroundImage: url("#{$pf-global--image-path}/pfbg_576.jpg");
  --pf-c-background-image--Filter: url("#{$pf-global--image-path}/background-filter.svg#image_overlay");

  background-image: var(--pf-c-background-image--BackgroundImage);
  filter: var(--pf-c-background-image--Filter);

   @media (min-width: $pf-global--breakpoint--sm) {
     --pf-c-background-image--BackgroundImage: url("#{$pf-global--image-path}/pfbg_768.jpg");
    }
    ...the rest 
}
```
then a consumer could overwrite those like any other CSS Variable, and also will only need to provide the breakpoints that matter to them.

2. Strip the image paths out of the css bundle at build time (to prevent 404's), and put together a prop system for this
```tsx
import { StyleSheet } from '@patternfly/react-styles';
import { Breakpoints, css } from '../../styles/breakpoints'; //not at all sure on this (didn't check)

type BackgroundImageSrcSizes =  { // again this is psuedo code
  [P in keyof Breakpoints]?: string;
};

interface Props {
  src: BackgroundImageSrcSizes | string;
}

const BackgroundImage = ({ src, className }) => {
  const bgStyles = {};
  if (typeof src === 'string') {
    bgStyles.backgroundImage = `url(${src})`;
  } else {
    Object.keys(src).forEach(bp => {
      styles[`@media min-width(${Breakpoints[bp]})`]: src[bp];  
    });
  }

  const  { bg, css } = StyleSheet.create({  bg: bgStyles })
  return <div className={css(bgStyles, styles.backgroundImage, className)} />;
}
```
Usage would look something like
```tsx
import { BackgroundImage } from '@patternfly/react-core';
import lgImage from '../assets/lg.png'; //using file-loader
import xsImage from '../assets/xs.png'; //using file-loader

const bg = <BackgroundImage src="https://example.com" />
const bgAdvanced = (
  <BackgroundImage 
    src={{
      lg: lgImage,
      xs: xsImage,
    }} 
  />
)
```
